# Copyright 2024 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: skaffold/v4beta1
kind: Config
metadata:
  name: extraction-service
requires:
  - path: ../../common
    configs: [common]

build:
  artifacts:
  - image: extraction-service
    docker:
      cacheFrom:
        - extraction-service
        - extraction-service:latest
    requires:
      - image: common
        alias: BASE_IMG
    sync:
      infer:
        - '**/*.py'
        - '**/*.json'
  googleCloudBuild: {}

portForward:
- resourceType: service
  resourceName: extraction-service
  port: 80
  localPort: 8892

profiles:
- name: prod
  deploy:
    kubectl: { }
  manifests:
    kustomize:
      paths:
      - ./kustomize/prod
    # Substitute system's environment vars to env.properties.rendered
    hooks:
      before:
        - host:
            dir: ./kustomize/base
            command: ["sh", "-c",
                      "envsubst < env.properties > env.properties.rendered"]
      after:
        - host:
            dir: ./kustomize/base
            command: ["sh", "-c", "rm env.properties.rendered"]

- name: dev
  deploy:
    kubectl: { }
  manifests:
    kustomize:
      paths:
      - ./kustomize/dev
    # Substitute system's environment vars to env.properties.rendered
    hooks:
      before:
        - host:
            dir: ./kustomize/base
            command: ["sh", "-c",
                      "envsubst < env.properties > env.properties.rendered"]
      after:
        - host:
            dir: ./kustomize/base
            command: ["sh", "-c", "rm env.properties.rendered"]